Timeline  Plugin - Table Sorting
dbeck121/CPI-Helper-Chrome-Extension pull request #166
Opened 2024-05-06 19:17 UTC by DevGregor

This makes the table of the timeline plugin sortable.

2024-05-06 23:06 UTC, incpi requested changes

2024-05-06 23:06 UTC, incpi commented on plugins/timeline.js
> +	A simple, lightweight jQuery plugin for creating sortable tables.
Hello,

This seems to be the wrong place where you add this library.

It should go to the lib/scematic folder. So it should be accessible everywhere and maintain property. As maybe tablesort.js or something suitable.

 
Thanks,
Omkar

2024-05-07 06:05 UTC, DevGregor commented on plugins/timeline.js
> +	A simple, lightweight jQuery plugin for creating sortable tables.
Hello Omkar

Yes, this script is from Fomantic. I wasn't sure where to put it so I put it together with the plugin where I needed it.

2024-05-07 12:18 UTC, incpi commented on plugins/timeline.js
> +	A simple, lightweight jQuery plugin for creating sortable tables.
Hello,

FYI,You can also use icons [SAP web UI](https://dbeck121.github.io/CPI-Helper-Chrome-Extension/?page=development) for lock, unlock similar to inline debug mode.

No change requested. Thanks a lot.

2024-05-07 16:53 UTC, incpi commented
Hello,

FYI,You can also use icons [SAP web UI](https://dbeck121.github.io/CPI-Helper-Chrome-Extension/?page=development) for lock, unlock similar to inline debug mode.

No change requested. Thanks a lot.

2024-05-07 23:10 UTC, DevGregor commented
Tried to make a separate draft Pull request but I don't know how or it either doesn't work.

2024-05-08 13:24 UTC, merged

2024-05-08 13:44 UTC, dbeck121 commented
No worries :-)

I pulled your changes and just in case you want to make changes, create another one.

Thanks for the contribution. I like your plugin. Will be released with next version.